### PR TITLE
Whitelist dokku commands

### PR DESCRIPTION
**Pull request by scjody**
Add the ability to whitelist the dokku commands that users can run, globally or per-app.

@bpostlethwaite Please review.

### CODE REVIEW

**Comment by bpostlethwaite** [comment]
Looks good to me :dancer:

**Comment by scjody** [comment]
@josegonzalez If you have any thoughts on this (especially on the [secure multi-tenancy section](https://github.com/dokku-community/dokku-acl/blob/49bb60317a5e4daba29a73666a830ea5af368f5f/README.md#secure-multi-tenancy) I added to the README) I'd appreciate those too!

**Comment by josegonzalez** [comment]
Acl usually lets you do something like

```
acl:add user group
acl:remove user group
acl:list-groups
acl:user-permissions
```

etc. I'd prefer that sort of interface, and then people can whitelist/blacklist perms for specific users/groups. You can even keep the special `admin` user around if you'd like.

**Comment by scjody** [comment]
@josegonzalez Groups are an interesting idea, but they would make this PR a lot more complicated.

First of all, the existing plugin already lets you run `acl:add user app` so we'd need a second "add" command for groups, which would be a bit confusing.

Secondly, storing and querying which users are in which group would add a fair bit of complexity to the implementation of this PR, and it would make configuration more complex. Instead of two lists of commands, the administrator would have to configure two lists of commands _per group_, increasing the chances of configuration errors.

I think if someone needs group functionality they can implement it in their own PR. Does that seem reasonable? I don't think anything in this PR prevents that from being done in the future.

**Comment by josegonzalez** [comment]
Fair enough.

**Review by josegonzalez — APPROVED** [review]

**Pull request merged**
